name: Go build-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Fetch deps
        run: make -f ci/Makefile --include-dir ci deps
      - name: Build
        run: make -f ci/Makefile --include-dir ci build
      - name: Test
        run: make -f ci/Makefile --include-dir ci test
